### ISSUE TITLE
[Thymeleaf] Layout Dialect

### ISSUE THREAD

**Issue by kamenitxan** [perwendel/spark-template-engines#19]
Hi,
is it possible to use Thymeleaf Layout Dialect?
https://github.com/ultraq/thymeleaf-layout-dialect

I tryed to extend thymeleaf template engine, but without success

**Comment by perwendel** [comment]
Hi,

Please ask tech questions on the spark google group https://groups.google.com/forum/#!forum/sparkjava

ping @dvaillant (author of thymeleaf engine)
