### ISSUE TITLE
hello.vm mentioned ...

### ISSUE THREAD

**Issue by agautam-hs** [perwendel/spark-template-engines#24]
... yet file is not in the repo :-(

**Comment by tipsy** [comment]
Seems it's .wm for some reason: https://github.com/perwendel/spark-template-engines/blob/master/spark-template-velocity/src/test/resources/hello.wm

**Comment by tipsy** [comment]
Fixed now: https://github.com/perwendel/spark-template-engines/blob/master/spark-template-velocity/src/test/resources/hello.vm

Thank you!

**Comment by agautam-hs** [comment]
Thanks Dave.

Sent from my iPhone

On Feb 10, 2016, at 6:27 PM, David <notifications@github.com<mailto:notifications@github.com>> wrote:


Fixed now: https://github.com/perwendel/spark-template-engines/blob/master/spark-template-velocity/src/test/resources/hello.vm<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_perwendel_spark-2Dtemplate-2Dengines_blob_master_spark-2Dtemplate-2Dvelocity_src_test_resources_hello.vm&d=CwMCaQ&c=Y88mj8G9kqbn8Ggg2-NXMw&r=xnO0tfku-bhkJ1CNBZbzs1SUTQPF_LPVtf_QQsYeKQ4&m=0i0SLIwqWX3yrk01Ks9M8Ae14gxCb9UrzjAL-ElQVXM&s=WCNMM-16HH43HQYCXX7_HF4xwyn5_b8FiPLRO19urao&e=>

Thank you!
