### ISSUE TITLE
Thymeleaf 3

### ISSUE THREAD

**Issue by mcjp78** [perwendel/spark-template-engines#29]
Will this be updated to support thymeleaf 3?

**Comment by tipsy** [comment]
Sure, would you like to create a pull request?

**Comment by mcjp78** [comment]
I can if needed, but all I think it needs is a dependency bump in maven

**Comment by mthmulders** [comment]
The [Thymeleaf 3 ten-minute migration guide](http://www.thymeleaf.org/doc/articles/thymeleaf3migration.html) states that 

> existing Thymeleaf templates are almost 100% compatible with Thymeleaf 3

So I don't think there would be much use in maintaining seperate Thymeleaf 2 and Thymeleaf 3 support.

As for me, I would like Thymeleaf 3 support. Apart from the announced performance improvements, it will probably be easier to use features like ["Link URLs"](http://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf.html#link-urls).

@mcjp78, if you don't have time to create a PR, let me know, I'll be more than happy to create one if needed.

**Comment by mcjp78** [comment]
I do, but I do not know how to properly migrate it. You can do it :)

On Sep 4, 2016, at 11:01 AM, Maarten Mulders <notifications@github.com<mailto:notifications@github.com>> wrote:


The Thymeleaf 3 ten-minute migration guide<http://www.thymeleaf.org/doc/articles/thymeleaf3migration.html> states that

existing Thymeleaf templates are almost 100% compatible with Thymeleaf 3

So I don't think there would be much use in maintaining seperate Thymeleaf 2 and Thymeleaf 3 support.

As for me, I would like Thymeleaf 3 support. Apart from the announced performance improvements, it will probably be easier to use features like "Link URLs"<http://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf.html#link-urls>.

@mcjp78<https://github.com/mcjp78>, if you don't have time to create a PR, let me know, I'll be more than happy to create one if needed.

-
