### ISSUE TITLE
Please deploy project to maven central

### ISSUE THREAD

**Issue by serge-nikitin** [perwendel/spark-template-engines#31]
I can not use spark-template-handlebars, becouse HandlebarsTemplateEngine. has private field: private Handlebars handlebars.

So I can not add my helpers to it. This is fixed in current source code, but in maven repo only old version.

http://mvnrepository.com/artifact/com.sparkjava/spark-template-handlebars

Can you update maven repo?

**Comment by tipsy** [comment]
Has been done, finally.
