### ISSUE TITLE
All current issues and update for all templating systems

### ISSUE THREAD

**Issue by AzureusNation** [perwendel/spark-template-engines#38]
Hi Guys,

Just a quick issue for myself really.

I'm going though updating all of the pom's including dependencies and creating unit tests for all of the template engines.

Another thing I'll add if I can get to it is to add Jinjava support as well.

PR will fix: ~~#25~~ #29 #34 #36
# Checklist
- [x] Add Jinjava support - PR #39 
- [x] Unify all pom's - _Will be committed in the next PR_

**Update all dependencies**
- [x] FreeMarker
- [x] Handlebars
- [x] Jade
- [x] Jetbrick _This will only be updated to version 2.1.1 as there is currently a issue with 2.1.2 that I have logged_
- [x] JinJava
- [x] Mustache
- [x] Pebble
- [x] ThymeLeaf
- [x] Velocity
- [x] Water

**Update all readme's**
- [x] FreeMarker
- [x] Handlebars
- [x] Jade
- [x] Jetbrick
- [x] JinJava
- [x] Mustache
- [x] Pebble
- [x] ThymeLeaf
- [x] Velocity
- [x] Water

**Create tests and test utilities**
- [x] FreeMarker
- [x] Handlebars
- [x] Jade
- [x] Jetbrick
- [x] JinJava
- [x] Mustache
- [x] Pebble
- [x] ThymeLeaf
- [x] Velocity
- [x] Water

**PR is ready!** #40

**Comment by tipsy** [comment]
Could you split them into different PRs?

**Comment by AzureusNation** [comment]
Possibly, I was going to update them all to the latest versions which should just fix a few in one hit. I'll try my best.

**Comment by tipsy** [comment]
You don't have to split every update into separate PRs, just the commit adding Jinjava support.

**Comment by AzureusNation** [comment]
Created PR #39 to fix #25

**Comment by met68** [comment]
Is there only one person maintaining the Spark templates? I keep running into issues with Pebble templates, all to do with the fact that Spark currently only supports Pebble version 1.4.4. Any idea when this might be updated to a more current (ideally THE current) version of Pebble?

**Comment by tipsy** [comment]
> Is there only one person maintaining the Spark templates?

Well, it's open source. @perwendel (the founder/main maintainer of Spark) works mostly on the core-framework. I work mainly on new features for the core, and web-stuff. @AzureusNation is doing a great job fixing up all the template engines, and I'll merge his changes once he's done. Maybe you could help him somehow (if he wants help?).

> P.S. Am I the only person in the world using Spark with Pebble?

Probably one of very few. Most people use freemarker or velocity, then comes handlebars and mustache. Then maybe jade/thymeleaf? Pebble is a port of Twig (which I think is a PHP template engine?).

If you can't wait, it's pretty easy to use Pebble directly in your project, you don't really need to use Spark's wrapper.

**Comment by met68** [comment]
Thanks for your quick reply and yes, I will probably have to use Pebble directly. I would be glad to help, but, alas, I am just getting my feet wet with Java and so would be of little use, I fear. My background is as a relative novice PHP guy and yes, Twig is a PHP templating engine.

**Comment by tipsy** [comment]
If your goal is to get into Java web development with server side rendering, I recommend trying out freemarker. It's very mature, has good IDE support and a lot of powerful features.

**Comment by AzureusNation** [comment]
@tipsy @met68 I will finish this Sunday at the latest.

**Comment by met68** [comment]
@tipsy Thanks. I have taken at cursory glance at Velocity and Freemaker, but feel Pebble (and Twig) are more powerful, especially with things like filters, which I tend to use quite a bit. I have tried to copy-paste the PebbleTemplateEngine class here into my project and update the pom dependency to Pebble 2.2.2 and while this did work, kind of, it did somehow screw-up the charset (I am building a multi-language website which includes German and all the Umlauts broke). I am now back to working with the existing spark-template-pebble 2.3 and using one or two workarounds, until @AzureusNation will hopefully get around to updating spark-template-pebble. As I said, I really appreciate the time you guys dedicate to this!

**Comment by AzureusNation** [comment]
@met68 I will be pushing tomorrow for sure. Just also creating a PR for something else but will now be working on the templates.

**Comment by AzureusNation** [comment]
Hmm. I don't know whether to push and create the PR with the current docs or strip them out and update them later... thoughts @tipsy

**Comment by tipsy** [comment]
Won't make much difference. Feel free to just make one giant PR if that's easier.

**Comment by tipsy** [comment]
@AzureusNation did you give up on this?

**Comment by tipsy** [comment]
Took over and fixed most of these
