### ISSUE TITLE
Velocity UTF-8 Problem

### ISSUE THREAD

**Issue by rootturk** [perwendel/spark-template-engines#49]
Hi Everyone,

I before thanks your develop Spark Web Framework. 

I start [this tutorial](https://sparktutorials.github.io/2016/06/10/spark-basic-structure.html  ) and develop demo projects. Everything was going well but I noticed a problem. Velocity Template Engine UTF-8 character problem on rendered html page. I research other projects and google, stackoverflow but can not resolve problem.

Waiting your helps.

Thanks.

![screen shot 2016-12-25 at 05 50 37](https://cloud.githubusercontent.com/assets/848297/21469535/b2d94d2a-ca5d-11e6-8e00-35ab9331292d.png)

**Comment by tipsy** [comment]
You need to supply the VelocityEngine with the utf-8 charset. This will be default in the next release of the template-engine project, but for now you can do:

```
public static String render(String templatePath, Map<String, Object> model) {
    VelocityEngine velocityEngine = new VelocityEngine(getEngineProperties());
    StringWriter writer = new StringWriter();
    velocityEngine.getTemplate(templatePath, StandardCharsets.UTF_8.name()).merge(new VelocityContext(model), writer);
    return compressHtml(writer.toString());
}
```

**Comment by rootturk** [comment]
@tipsy thanks for your response. I change my render method code, resolved this problem. I grateful.
