### ISSUE TITLE
Configure thymeleaf-extras-java8time

### ISSUE THREAD

**Issue by weickmanna** [perwendel/spark-template-engines#63]
Thymeleaf does not support Java8 time out of the box. Having to work around this slows development down.

There is https://github.com/thymeleaf/thymeleaf-extras-java8time that adds this feature. But it needs to be configured:

```
TemplateEngine templateEngine = new TemplateEngine();
templateEngine.addDialect(new Java8TimeDialect());
```

It is not possible without reflection hack to configure org.thymeleaf.TemplateEngine through spark.template.thymeleaf.ThymeleafTemplateEngine, because the field is private.

Spark is requiring Java8 anyways, so we could enable this by default already ...

**Comment by tipsy** [comment]
I'd be happy to merge a PR.
